<?php

declare(strict_types=1);

namespace Directive\Service\AppManagement;

/**
 * Read-only VO wrapping the app-info JSON file.
 *
 * Expected JSON shape (generated by `directive ci:appinfo`):
 *   { name, version, env, commitId, branch, tag, buildNumber, builtAt, builtBy }
 */
final class AppInfo implements AppInfoInterface
{
    /** @param array<string, mixed> $data */
    public function __construct(private readonly array $data = []) {}

    public function getName(): string
    {
        return (string) ($this->data['name'] ?? '');
    }

    public function getVersion(): string
    {
        return (string) ($this->data['version'] ?? '');
    }

    public function getCommitId(): string
    {
        return (string) ($this->data['commitId'] ?? '');
    }

    public function getBranch(): string
    {
        return (string) ($this->data['branch'] ?? '');
    }

    public function getTag(): string
    {
        return (string) ($this->data['tag'] ?? '');
    }

    public function getBuildNumber(): string
    {
        return (string) ($this->data['buildNumber'] ?? '');
    }

    public function getBuiltAt(): string
    {
        return (string) ($this->data['builtAt'] ?? '');
    }

    public function getBuiltBy(): string
    {
        return (string) ($this->data['builtBy'] ?? '');
    }

    /** @return array<string, mixed> */
    public function readVersion(): array
    {
        return array_intersect_key($this->data, array_flip(['name', 'version']));
    }

    /** @return array<string, mixed> */
    public function readAll(): array
    {
        return array_intersect_key(
            $this->data,
            array_flip(['name', 'version', 'commitId', 'branch', 'tag', 'buildNumber', 'builtAt', 'builtBy']),
        );
    }
}
