<?php

declare(strict_types=1);

namespace Directive\Console;

use Directive\Cli\DirectiveCommand;
use Directive\Service\Configuration\Configuration;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Generates var/cache/config.php -- a PHP cache of resolved, non-sensitive configuration.
 *
 * All service config keys (logging, security, http, …) live in the single shared
 * Configuration dictionary, so the cache captures every non-sensitive key
 * in one entry keyed by the user's config class name.
 *
 * Sensitive variables (names containing SECRET, PASSWORD, KEY, TOKEN, ...) are NEVER
 * written to the cache; they continue to be resolved from $_ENV at every startup.
 *
 * The cache is a PHP file returning an associative array:
 *
 *   return [
 *       'App\Config\AppConfig' => ['APP_ENV' => 'production', 'LOG_LEVEL' => 'info', ...],
 *   ];
 *
 * Run this command in CI/CD after deploy to avoid redundant $_ENV parsing on every request.
 */
#[AsCommand(
    name: 'config:compile',
    description: 'Compile resolved configuration into var/cache/config.php.',
)]
final class ConfigCompileCommand extends DirectiveCommand
{
    private const SENSITIVE_PATTERN = '/SECRET|PASSWORD|PASSWD|PWD|KEY|TOKEN|CREDENTIAL|PRIVATE|CERT/i';

    private const CACHE_DIR  = 'var/cache';
    private const CACHE_FILE = 'var/cache/config.php';

    protected function executeCommand(InputInterface $input, OutputInterface $output): int
    {
        if (!is_dir(self::CACHE_DIR)) {
            $output->writeln(sprintf(
                '<error>Cache directory "%s" does not exist. Create it before running config:compile.</error>',
                self::CACHE_DIR,
            ));

            return self::FAILURE;
        }

        if (!is_writable(self::CACHE_DIR)) {
            $output->writeln(sprintf(
                '<error>Cache directory "%s" is not writable. Check permissions.</error>',
                self::CACHE_DIR,
            ));

            return self::FAILURE;
        }

        if (!$this->container->has(Configuration::class)) {
            $output->writeln('<comment>No Configuration bound in the container.</comment>');

            return self::SUCCESS;
        }

        /** @var Configuration $config */
        $config = $this->container->get(Configuration::class);
        $config->audit();

        $class       = get_class($config);
        $resolved    = $config->getAll();
        $definitions = $config->getDefinitions();

        $safe = [];

        foreach ($definitions as $key => $def) {
            if (preg_match(self::SENSITIVE_PATTERN, $key)) {
                continue;
            }

            $safe[$key] = array_key_exists($key, $resolved) ? $resolved[$key] : $def['default'];
        }

        $cacheData = $safe !== [] ? [$class => $safe] : [];

        $header  = "<?php\n\ndeclare(strict_types=1);\n\n";
        $comment = "// Generated by config:compile -- do not edit manually.\n";
        $comment .= "// Sensitive variables are resolved from \$_ENV at runtime.\n\n";
        $php  = $header . $comment . 'return ';
        $php .= var_export($cacheData, return: true);
        $php .= ";\n";

        if (file_put_contents(self::CACHE_FILE, $php) === false) {
            $output->writeln(sprintf('<error>Failed to write cache file "%s".</error>', self::CACHE_FILE));

            return self::FAILURE;
        }

        $output->writeln(sprintf(
            '<info>Config cache written to %s (%d variable(s) compiled)</info>',
            self::CACHE_FILE,
            count($safe),
        ));

        return self::SUCCESS;
    }
}
