<?php

declare(strict_types=1);

namespace Directive\Console;

use Directive\Cli\DirectiveCommand;
use Directive\Http\Middleware\HttpConfigInterface;
use Directive\Service\AppIdentity\AppIdentityConfigInterface;
use Directive\Service\Configuration\AbstractConfiguration;
use Directive\Service\Logging\LoggingConfigInterface;
use Directive\Service\Security\Antivirus\AntivirusConfigInterface;
use Directive\Service\Security\SecurityConfigInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Generates var/cache/config.php -- a PHP cache of resolved, non-sensitive configuration.
 *
 * Sensitive variables (names containing SECRET, PASSWORD, KEY, TOKEN, ...) are NEVER
 * written to the cache; they continue to be resolved from $_ENV at every startup.
 *
 * The cache is a PHP file returning an associative array:
 *
 *   return [
 *       'App\Config\AppConfig' => ['APP_ENV' => 'production', ...],
 *       'Directive\Service\Logging\DefaultLoggingConfig' => [...],
 *   ];
 *
 * Run this command in CI/CD after deploy to avoid redundant $_ENV parsing on every request.
 */
#[AsCommand(
    name: 'config:compile',
    description: 'Compile resolved configuration into var/cache/config.php.',
)]
final class ConfigCompileCommand extends DirectiveCommand
{
    private const SENSITIVE_PATTERN = '/SECRET|PASSWORD|PASSWD|PWD|KEY|TOKEN|CREDENTIAL|PRIVATE|CERT/i';

    private const CACHE_DIR  = 'var/cache';
    private const CACHE_FILE = 'var/cache/config.php';

    /** @var list<string> */
    private const SERVICE_INTERFACES = [
        LoggingConfigInterface::class,
        AppIdentityConfigInterface::class,
        AntivirusConfigInterface::class,
        SecurityConfigInterface::class,
        HttpConfigInterface::class,
    ];

    protected function executeCommand(InputInterface $input, OutputInterface $output): int
    {
        // Validate cache directory is writable
        if (!is_dir(self::CACHE_DIR)) {
            $output->writeln(sprintf(
                '<error>Cache directory "%s" does not exist. Create it before running config:compile.</error>',
                self::CACHE_DIR,
            ));

            return self::FAILURE;
        }

        if (!is_writable(self::CACHE_DIR)) {
            $output->writeln(sprintf(
                '<error>Cache directory "%s" is not writable. Check permissions.</error>',
                self::CACHE_DIR,
            ));

            return self::FAILURE;
        }

        $configs = $this->resolveConfigs();

        if ($configs === []) {
            $output->writeln('<comment>No AbstractConfiguration bound in the container.</comment>');

            return self::SUCCESS;
        }

        // Build the cache data: class-name => non-sensitive resolved values
        $cacheData = [];

        foreach ($configs as $config) {
            $config->audit();

            $class       = get_class($config);
            $resolved    = $config->getAll();
            $definitions = $config->getDefinitions();

            $safe = [];
            foreach ($definitions as $key => $def) {
                if (preg_match(self::SENSITIVE_PATTERN, $key)) {
                    // Never write sensitive variables to the cache
                    continue;
                }

                $safe[$key] = array_key_exists($key, $resolved) ? $resolved[$key] : $def['default'];
            }

            if ($safe !== []) {
                $cacheData[$class] = $safe;
            }
        }

        $header  = "<?php\n\ndeclare(strict_types=1);\n\n";
        $comment = "// Generated by config:compile -- do not edit manually.\n";
        $comment .= "// Sensitive variables are resolved from \$_ENV at runtime.\n\n";
        $php  = $header . $comment . 'return ';
        $php .= var_export($cacheData, return: true);
        $php .= ";\n";

        if (file_put_contents(self::CACHE_FILE, $php) === false) {
            $output->writeln(sprintf('<error>Failed to write cache file "%s".</error>', self::CACHE_FILE));

            return self::FAILURE;
        }

        $output->writeln(sprintf(
            '<info>Config cache written to %s (%d configuration(s) compiled)</info>',
            self::CACHE_FILE,
            count($cacheData),
        ));

        return self::SUCCESS;
    }

    /**
     * Collect all AbstractConfiguration instances available in the container.
     *
     * @return list<AbstractConfiguration>
     */
    private function resolveConfigs(): array
    {
        $ids = array_merge([AbstractConfiguration::class], self::SERVICE_INTERFACES);

        $configs = [];
        $seen    = [];

        foreach ($ids as $id) {
            if (!$this->container->has($id)) {
                continue;
            }

            $obj = $this->container->get($id);

            if (!($obj instanceof AbstractConfiguration)) {
                continue;
            }

            $class = get_class($obj);

            if (isset($seen[$class])) {
                continue;
            }

            $seen[$class] = true;
            $configs[]    = $obj;
        }

        return $configs;
    }
}
